name: flutter_my_doctor_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.4.0
  flutter_markdown: ^0.6.17

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Path to your icon image
  adaptive_icon_background: "#ffffff"  # Background color (for Android adaptive icons)
